// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.1
// source: graph.api.proto

package graphproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Link defines a link in the link graph store.
type Link struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid        []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Url         string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	RetrievedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=retrieved_at,json=retrievedAt,proto3" json:"retrieved_at,omitempty"`
}

func (x *Link) Reset() {
	*x = Link{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_graph_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_graph_api_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Link) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Link) GetRetrievedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RetrievedAt
	}
	return nil
}

// Edge defines an edge in the link graph store.
type Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SrcUuid   []byte                 `protobuf:"bytes,2,opt,name=src_uuid,json=srcUuid,proto3" json:"src_uuid,omitempty"`
	DestUuid  []byte                 `protobuf:"bytes,3,opt,name=dest_uuid,json=destUuid,proto3" json:"dest_uuid,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Edge) Reset() {
	*x = Edge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_graph_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_graph_api_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *Edge) GetSrcUuid() []byte {
	if x != nil {
		return x.SrcUuid
	}
	return nil
}

func (x *Edge) GetDestUuid() []byte {
	if x != nil {
		return x.DestUuid
	}
	return nil
}

func (x *Edge) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// RemoveStaleEdgesQuery defines a query for removing stale edges from the
// graph store.
type RemoveStaleEdgesQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUuid      []byte                 `protobuf:"bytes,1,opt,name=from_uuid,json=fromUuid,proto3" json:"from_uuid,omitempty"`
	UpdatedBefore *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_before,json=updatedBefore,proto3" json:"updated_before,omitempty"`
}

func (x *RemoveStaleEdgesQuery) Reset() {
	*x = RemoveStaleEdgesQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveStaleEdgesQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStaleEdgesQuery) ProtoMessage() {}

func (x *RemoveStaleEdgesQuery) ProtoReflect() protoreflect.Message {
	mi := &file_graph_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStaleEdgesQuery.ProtoReflect.Descriptor instead.
func (*RemoveStaleEdgesQuery) Descriptor() ([]byte, []int) {
	return file_graph_api_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveStaleEdgesQuery) GetFromUuid() []byte {
	if x != nil {
		return x.FromUuid
	}
	return nil
}

func (x *RemoveStaleEdgesQuery) GetUpdatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedBefore
	}
	return nil
}

// Range specifies the [fromID, toID) range used when streaming Links or Edges.
type Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUuid []byte `protobuf:"bytes,1,opt,name=from_uuid,json=fromUuid,proto3" json:"from_uuid,omitempty"`
	ToUuid   []byte `protobuf:"bytes,2,opt,name=to_uuid,json=toUuid,proto3" json:"to_uuid,omitempty"`
	// Return results before this filter timestamp.
	TimeFilter *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=time_filter,json=timeFilter,proto3" json:"time_filter,omitempty"`
}

func (x *Range) Reset() {
	*x = Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_graph_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_graph_api_proto_rawDescGZIP(), []int{3}
}

func (x *Range) GetFromUuid() []byte {
	if x != nil {
		return x.FromUuid
	}
	return nil
}

func (x *Range) GetToUuid() []byte {
	if x != nil {
		return x.ToUuid
	}
	return nil
}

func (x *Range) GetTimeFilter() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeFilter
	}
	return nil
}

var File_graph_api_proto protoreflect.FileDescriptor

var file_graph_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x6b, 0x0a, 0x04, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x3d, 0x0a,
	0x0c, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x0b, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x64, 0x41, 0x74, 0x22, 0x8d, 0x01, 0x0a,
	0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x72, 0x63,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x72, 0x63,
	0x55, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x74, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x65, 0x73, 0x74, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x77, 0x0a, 0x15,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x6c, 0x65, 0x45, 0x64, 0x67, 0x65, 0x73,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x75,
	0x69, 0x64, 0x12, 0x41, 0x0a, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x65,
	0x66, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42,
	0x65, 0x66, 0x6f, 0x72, 0x65, 0x22, 0x7a, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x74,
	0x6f, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x6f,
	0x55, 0x75, 0x69, 0x64, 0x12, 0x3b, 0x0a, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x32, 0xbb, 0x01, 0x0a, 0x09, 0x4c, 0x69, 0x6e, 0x6b, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12,
	0x1a, 0x0a, 0x0a, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x05, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x1a, 0x05, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x1a, 0x0a, 0x0a, 0x55,
	0x70, 0x73, 0x65, 0x72, 0x74, 0x45, 0x64, 0x67, 0x65, 0x12, 0x05, 0x2e, 0x45, 0x64, 0x67, 0x65,
	0x1a, 0x05, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x05, 0x4c, 0x69, 0x6e, 0x6b, 0x73,
	0x12, 0x06, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0x05, 0x2e, 0x4c, 0x69, 0x6e, 0x6b, 0x30,
	0x01, 0x12, 0x18, 0x0a, 0x05, 0x45, 0x64, 0x67, 0x65, 0x73, 0x12, 0x06, 0x2e, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x1a, 0x05, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x30, 0x01, 0x12, 0x42, 0x0a, 0x10, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x6c, 0x65, 0x45, 0x64, 0x67, 0x65, 0x73, 0x12,
	0x16, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x53, 0x74, 0x61, 0x6c, 0x65, 0x45, 0x64, 0x67,
	0x65, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42,
	0x0d, 0x5a, 0x0b, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_graph_api_proto_rawDescOnce sync.Once
	file_graph_api_proto_rawDescData = file_graph_api_proto_rawDesc
)

func file_graph_api_proto_rawDescGZIP() []byte {
	file_graph_api_proto_rawDescOnce.Do(func() {
		file_graph_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_graph_api_proto_rawDescData)
	})
	return file_graph_api_proto_rawDescData
}

var file_graph_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_graph_api_proto_goTypes = []interface{}{
	(*Link)(nil),                  // 0: Link
	(*Edge)(nil),                  // 1: Edge
	(*RemoveStaleEdgesQuery)(nil), // 2: RemoveStaleEdgesQuery
	(*Range)(nil),                 // 3: Range
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_graph_api_proto_depIdxs = []int32{
	4, // 0: Link.retrieved_at:type_name -> google.protobuf.Timestamp
	4, // 1: Edge.updated_at:type_name -> google.protobuf.Timestamp
	4, // 2: RemoveStaleEdgesQuery.updated_before:type_name -> google.protobuf.Timestamp
	4, // 3: Range.time_filter:type_name -> google.protobuf.Timestamp
	0, // 4: LinkGraph.UpsertLink:input_type -> Link
	1, // 5: LinkGraph.UpsertEdge:input_type -> Edge
	3, // 6: LinkGraph.Links:input_type -> Range
	3, // 7: LinkGraph.Edges:input_type -> Range
	2, // 8: LinkGraph.RemoveStaleEdges:input_type -> RemoveStaleEdgesQuery
	0, // 9: LinkGraph.UpsertLink:output_type -> Link
	1, // 10: LinkGraph.UpsertEdge:output_type -> Edge
	0, // 11: LinkGraph.Links:output_type -> Link
	1, // 12: LinkGraph.Edges:output_type -> Edge
	5, // 13: LinkGraph.RemoveStaleEdges:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_graph_api_proto_init() }
func file_graph_api_proto_init() {
	if File_graph_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_graph_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Link); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Edge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveStaleEdgesQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graph_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_api_proto_goTypes,
		DependencyIndexes: file_graph_api_proto_depIdxs,
		MessageInfos:      file_graph_api_proto_msgTypes,
	}.Build()
	File_graph_api_proto = out.File
	file_graph_api_proto_rawDesc = nil
	file_graph_api_proto_goTypes = nil
	file_graph_api_proto_depIdxs = nil
}
