# Overrides for cockroachDB helm chart at:
# https://github.com/cockroachdb/helm-charts/tree/master/cockroachdb
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"
persistentVolume:
    enabled: true
    size: "100Mi"
statefulset:
  replicas: 1
single-node: true