# Overrides for elasticsearch helm chart at:
# https://github.com/elastic/helm-charts/tree/main/elasticsearch

# k8s scheduler will schedule statefullset pods using it's best effort policy
# depending on pod's resource requests.
antiAffinity: "soft"
# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

replicas: 1

# Request and allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "200m"
    memory: "512Mi"
# Request smaller persistent volumes.
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: null
  resources:
    requests:
      storage: "300Mi"
