# This k8s job runs a cockroachDB container and performs various operations on the app's cockroachDB
# container such as:
#           1. creates a database with the name "linkgraph".
#           2. runs migrations to create the necessary tables.

# Note: This job exits on completion.

apiVersion: batch/v1
kind: Job
metadata:
  name: cdb-ensure-schema
  namespace: usearch-data
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      containers:
      - name: cdb-schema
        imagePullPolicy: Always
        image: myckie/cdb-schema:latest
        args:
        # Database name
          - "linkgraph"
          # Database host value / url. [network-service-name].[namespace]
          - "cdb-cockroachdb-public.usearch-data:26257"
      restartPolicy: Never
